# Generated by Django 5.1.1 on 2025-01-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_friendrequest_options_alter_friendship_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_reverse_friend_request',
        ),
        migrations.RemoveConstraint(
            model_name='friendship',
            name='unique_reverse_friendship',
        ),
    ]
