# Generated by Django 4.2.6 on 2023-10-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='hostname',
        ),
    ]
