# Generated by Django 4.2.6 on 2023-10-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_remove_pageview_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='ip_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
